(TeX-add-style-hook
 "chapter2"
 (lambda ()
   (LaTeX-add-labels
    "fig:cern_complex"
    "fig:lhcb"
    "fig:cherenkov_media"
    "fig:TT"
    "fig:st_ot"
    "fig:em_shower"
    "fig:muon_partition"
    "fig:velo_assembly"
    "fig:velo_overview"
    "fig:velo_routing"
    "fig:velo_pitch"
    "chap2:calibration"
    "plot:postcal"
    "plot:velo_clustering"
    "chap2:headercrosstalk"
    "chap2:lumivolt"
    "fig:velo_lumi"
    "fig:velo_voltage"
    "fig:radiation_damage"
    "fig:velopix_datarate"
    "fig:velopix_layout"
    "chap2:velopix_calibration"
    "plot:velopix_thresholding"))
 :latex)

