(TeX-add-style-hook
 "chapter5"
 (lambda ()
   (LaTeX-add-labels
    "fig:storck_diagram"
    "tab:storck_filesfield"
    "sec:deduplication"
    "tab:workspace-api"
    "tab:file-api"
    "tab:storck_rest_api"
    "fig:storck-dockers"
    "fig:storck-gitlab"
    "fig:storck-web-interface"
    "listing:storck_client"
    "tab:storck_client"
    "sec:titania_data"
    "listing:data"
    "listing:plot"
    "listing:exploration"
    "listing:view"
    "fig:titania-weather"
    "listing:weather_upgrade"
    "listing:weather_change"
    "listing:weather_split"
    "listing:weather_webclass"
    "listing:weather_web_meta"
    "listing:weather_web_config"
    "listing:weather_web_main"
    "fig:titaniawebinterface"))
 :latex)

