name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: get the scripts
        run: sudo apt install wget; WGET -O fonts.zip https://fonts.google.com/download?family=EB%20Garamond; unzip fonts.zip -d egb; 
      - name: install the fonts
        run: mkdir ~/.fonts; cp egb/* fonts/; fc-cache -rv;
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: dissertation.tex
          latexmk_use_xelatex: true
      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: dissertation.pdf

